
version: '2.1'
services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - IMAGE_ARG_ALPINE_MIRROR=${IMAGE_ARG_ALPINE_MIRROR:-mirror.tuna.tsinghua.edu.cn}
    image: ${IMAGE_PREFIX:-cirepo}/${IMAGE_NAME:-jenkins}:${IMAGE_TAG:-lts-alpine}
    restart: always
    container_name: ${CONTAINER_HOST_NAME:-jenkins}
    hostname: ${CONTAINER_HOST_NAME:-jenkins}
    ports:
    - "${JENKINS_EXTERNAL_PORT:-18083}:${JENKINS_PORT:-8080}"
    - "50000:50000/tcp"
    volumes:
    - volume-jenkins-master:/var/jenkins_home
    environment:
    - JENKINS_SLAVE_AGENT_PORT=50000

volumes:
  volume-jenkins-master: {}

networks:
  default:
    external: true
    name: oss-network
