
version: '2.1'
services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - IMAGE_ARG_ALPINE_MIRROR=${IMAGE_ARG_ALPINE_MIRROR:-mirror.tuna.tsinghua.edu.cn}
    container_name: ${CONTAINER_HOST_NAME:-standalone.jenkins}
    environment:
    - JENKINS_SLAVE_AGENT_PORT=50000
    hostname: ${CONTAINER_HOST_NAME:-standalone.jenkins}
    image: ${IMAGE_PREFIX:-cirepo/}${IMAGE_NAME:-jenkins}:${IMAGE_TAG:-lts-alpine}
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.jenkins}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/jenkins/standalone}
    networks:
      local-network:
        ipv4_address: ${IPV4_ADDRESS:-172.16.238.33}
        #ipv6_address: ${IPV6_ADDRESS:-2001:3984:3989::33}
    ports:
    - "${EXTERNAL_JENKINS_8080_PORT:-18083}:8080"
    - "${EXTERNAL_JENKINS_50000_PORT:-50000}:50000/tcp"
    restart: always
    volumes:
    - jenkins_home:/var/jenkins_home

# `docker network create --driver=bridge --ipam-driver=default --subnet=172.16.238.0/24 local-network`
networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64

volumes:
  jenkins_home:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/jenkins_home
      o: bind
