
version: '2.1'
services:
  jenkins-master:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - IMAGE_ARG_ALPINE_MIRROR=${IMAGE_ARG_ALPINE_MIRROR:-mirror.tuna.tsinghua.edu.cn}
    image: ${IMAGE_PREFIX:-cirepo}/${IMAGE_NAME:-jenkins}:${IMAGE_TAG:-lts-alpine}
    restart: always
    container_name: ${CONTAINER_HOST_NAME:-jenkins}
    hostname: ${CONTAINER_HOST_NAME:-jenkins}
    networks:
      local-network:
        ipv4_address: 172.16.238.33
        #ipv6_address: 2001:3984:3989::33
    ports:
    - "${JENKINS_EXTERNAL_PORT:-18083}:${JENKINS_PORT:-8080}"
    - "50000:50000/tcp"
    volumes:
    - jenkins_home:/var/jenkins_home
    environment:
    - JENKINS_SLAVE_AGENT_PORT=50000

networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64

volumes:
  jenkins_home:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/jenkins_home
      o: bind
